env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - main: ./cmd/heznode/main.go
    binary: heznode
    id: heznode
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    hooks:
      pre:
        - cmd: bash -c "GOOS={{ .Os }} GOARCH={{ .Arch }} packr2"
          dir: db
      post:
        - cmd: packr2 clean
          dir: db

archives:
  - id: heznode
    wrap_in_directory: true
    files:
      - LICENSE
      - cmd/heznode/README.md
      - cmd/heznode/cfg.api.toml
      - cmd/heznode/cfg.builder.toml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'