blank_issues_enabled: false
contact_links:
  - name: Hermez Docs
    url: https://docs.hermez.io/
    about: Official Hermez Documentation
  - name: Telegram Group
    url: https://t.me/hermez_network
    about: Official Hermez Telegram Group
  - name: Discord Community
    url: https://discord.com/invite/AczuUXDA2N
    about: Official Hermez Discord Comunnity
