blank_issues_enabled: false
contact_links:
  - name: Hermez Website
    url: https://hermez.io/
    about: Official Hermez Website
  - name: Telegram Group
    url: https://t.me/hermez_network
    about: Official Hermez Telegram Group
  - name: Discord Community
    url: https://discord.com/invite/AczuUXDA2N
    about: Official Hermez Discord Comunnity
  - name: Twitter
    url: https://twitter.com/hermez_network
    about: Official Hermez Twitter