name: Docker
on: [ push, pull_request ]
jobs:
  docker:
    strategy:
      matrix:
        go-version: [ 1.14.x ]
        goarch: [ "amd64" ]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      env:
        GOARCH: ${{ matrix.goarch }}
    - name: Checkout code
      uses: actions/checkout@v2

    - name: docker build
      run: make docker-build
    
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: hermeznet/hermeznode
        tag_with_ref: true
